/* Generated By:JavaCC: Do not edit this line. PizzaLangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PizzaLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BUY = 8;
  /** RegularExpression Id. */
  int MIX = 9;
  /** RegularExpression Id. */
  int SPREAD = 10;
  /** RegularExpression Id. */
  int TOP = 11;
  /** RegularExpression Id. */
  int BAKE = 12;
  /** RegularExpression Id. */
  int PIZZA = 13;
  /** RegularExpression Id. */
  int DOUGH = 14;
  /** RegularExpression Id. */
  int KNEAD = 15;
  /** RegularExpression Id. */
  int RISE = 16;
  /** RegularExpression Id. */
  int ROLL = 17;
  /** RegularExpression Id. */
  int OLIVE = 18;
  /** RegularExpression Id. */
  int OIL = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int TOMATO = 21;
  /** RegularExpression Id. */
  int PESTO = 22;
  /** RegularExpression Id. */
  int SAUCE = 23;
  /** RegularExpression Id. */
  int WITH = 24;
  /** RegularExpression Id. */
  int CHEESE = 25;
  /** RegularExpression Id. */
  int MUSHROOMS = 26;
  /** RegularExpression Id. */
  int SPINACH = 27;
  /** RegularExpression Id. */
  int PEPPERONI = 28;
  /** RegularExpression Id. */
  int IN = 29;
  /** RegularExpression Id. */
  int A = 30;
  /** RegularExpression Id. */
  int PREHEATED = 31;
  /** RegularExpression Id. */
  int OVEN = 32;
  /** RegularExpression Id. */
  int NOW = 33;
  /** RegularExpression Id. */
  int EAT = 34;
  /** RegularExpression Id. */
  int IT = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\".\"",
    "\"!\"",
    "\",\"",
    "\"Buy\"",
    "\"Mix\"",
    "\"Spread\"",
    "\"Top\"",
    "\"Bake\"",
    "\"pizza\"",
    "\"dough\"",
    "\"knead\"",
    "\"rise\"",
    "\"roll\"",
    "\"olive\"",
    "\"oil\"",
    "\"and\"",
    "\"tomato\"",
    "\"pesto\"",
    "\"sauce\"",
    "\"with\"",
    "\"cheese\"",
    "\"mushrooms\"",
    "\"spinach\"",
    "\"pepperoni\"",
    "\"in\"",
    "\"a\"",
    "\"preheated\"",
    "\"oven\"",
    "\"Now\"",
    "\"eat\"",
    "\"it\"",
  };

}
